### ISSUE TITLE
facing issue with gradle git zoltu plugin

### ISSUE THREAD

**Issue by vamshers** [Zoltu/Gradle.Plugin.Versioning#25]
I am using below zoltu plugin for managing the patch version automatically.

As this  plugin requires code to be taged using v.major.minor convention, I have tagged the code with v0.1 and the tag is reachable form the HEAD.

But still I am getting below error -

  ```
      What went wrong: A problem occurred evaluating root project 'report-service'.

        Your repository must have at least one tag in it for git-versioning to work. Recommended solution: git tag v0.0
```
and git tag show there is a tag and i have check the revision history and this tag is reachable from the branch I am working on -

```
$ git tag
v0.1
```

Do anyone have any clue what the issue is. This a blocker for me.
Thanks in advance for any help..

**Comment by MicahZoltu** [comment]
What is the output if you run `git describe`?  That is (effectively) the command this plugin is using to derive the version.

**Comment by VonC** [comment]
@MicahZoltu  This seems to be [related to the nature of the tag](https://stackoverflow.com/a/73538646/6309) (annotated vs. lightweight)

**Comment by MicahZoltu** [comment]
Ah, that does ring a bell for me.  It was a long time ago, but I vaguely remember something about that when working on this plugin.  I want to say that making it working for all tag types was sufficiently hard that I punted on it.  I could be misremembering though.

**Comment by vamshers** [comment]
Yes. Like @VonC mentioned - it is expecting an annotated tag.  It will be helpful if the project documentation mentions this specifically.

**Comment by MicahZoltu** [comment]
It appears this could be fixed by changing https://github.com/Zoltu/Gradle.Plugin.Versioning/blob/20fee206a2c8a2fdeac10dcb290e0543dca7a5ad/src/main/kotlin/com/zoltu/gradle/plugin/GitVersioning.kt#L68
to
```kotlin
return git.describe().setLong(true).setTags(true).call() ?: throw Exception("Your repository must have at least one tag in it for git-versioning to work.  Recommended solution: git tag v0.0")
```

Unfortunately, I haven't worked with Kotlin/Java for a while now and I no longer have a dev environment setup.  I also suspect that CI doesn't work anymore as I *suspect* that the appveyor account that was used is now defunct.  😖 

If someone wants to go through the leg work of implementing/testing this change and submitting a PR that moves the build system over to GitHub actions I wouldn't be against adding this, but at the moment I don't think adding it here is realistic.

I'll try to get the documentation updated at least.  Also, if someone wants to actively maintain this project I would happily mark this repository as deprecated and add a link to your maintained version in the Readme!

**Comment by MicahZoltu** [comment]
Docs updated at the least: https://github.com/Zoltu/Gradle.Plugin.Versioning/pull/26

This will also give us a chance to see if CI is still functional, as it *should* trigger a build.

**Comment by MicahZoltu** [comment]
TL;DR: Build system appears to work, but deploy system doesn't and fixing it is not a small task.  Will have to settle with just the docs update for now, sorry!

It does appear that AppVeyor is still mostly working with a minor modification.  Unfortunately, I can't actually publish because the underlying publish plugin has a security vulnerability and apparently felt that completely disabling the publishing plugin was the way to go.  I use a wrapper around that, but the wrapper publishes with itself so I cannot actually publish a fix for the wrapper because it needs to be updated before it can be used.  https://github.com/Zoltu/Gradle.Plugin.SimpleGradlePluginPublish/pull/1

**Comment by MicahZoltu** [comment]
I took a brief stab at adding `setTags(true)` in #27 but it appears that it the version of jgit I'm using doesn't have `setTags` as an option, which explains why I didn't use it when I built this originally.  I tried updating to latest version of jgit, but that requires also updating the version of Java being targeted.

All of these problems are solvable (publishing plugin, java version, jgit version) but requires someone willing to put in more effort than me.  I strongly encourage/support someone forking this repository and doing a better job with maintenance than me!  I think adding light tag support would be great.

In the meantime, I am going to close this issue now that I have updated the docs.  Sorry!
